name: linkrot
version: '0.982'
summary: linkrot
description: |
  This script searches a pdf for hyperlinks and tests them for active status or errors returned.
base: core18
confinement: classic


parts:
  linkrot:
    plugin: python
    python-version: python3
    source: .
 
apps:
  linkrot:
    command: bin/linkrot
