name: linkrot
version: '0.982'
summary: linkrot
description: |
  This script searches a pdf for hyperlinks and tests them for active status or errors returned.
base: core18
confinement: devmode
apps:
  linkrot:
    command: bin/linkrot
