name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to our community. Thank you for helping make this project better. We appricaite your feedback and look forward to addressing your issues.'
        pr-message: ' You are awesome! Thank you for contributing to our project. We really aprriciate you helping make this project better.'
