on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
jobs:
  steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.5.0
    - name: OWASP ZAP Full Scan
     uses: zaproxy/action-full-scan@v0.3.0
